Added Ottawa plenary presentations to meetings.md and 2019-Ottawa subdirectory
INTERMAGNET/intermagnet.github.io pull request #39
Opened 2019-08-30 06:14 UTC by ALewis-GA

2019-08-30 10:57 UTC, CharlesBlais requested changes
The header section delimited by "----" is required on every page.  Even though the page may render well, the "title" meta information part of the header is also used for the title of the page.

Replace

## Meetings

with

---
title: Meetings	
---

Tip: The "##" indicates a header of level 2.  A sub-section should there be "###" which indicated a header of level 3.

2019-08-31 02:45 UTC, ALewis-GA commented
Fixed the title meta information in meetings.md

2019-08-31 02:59 UTC, ALewis-GA commented
fixed title meta information

2019-09-04 12:15 UTC, CharlesBlais approved these changes

2019-09-04 12:15 UTC, merged